<a href="https://colab.research.google.com/github/sobiashakeel18/Sobia_INFO5731_Spring2026/blob/main/Assignment_2_Submission.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. Data Quality Check

1.1 Using Python (pandas, matplotlib, or seaborn), load and inspect the Assignment 2 dataset.

In [22]:
import pandas as pd

df = pd.read_csv("Assignment 2 dataset.csv")
df.head()


from google.colab import files
uploaded = files.upload()

Saving Assignment 2 dataset.csv to Assignment 2 dataset (3).csv

Write code to explore the data distribution (e.g., region, type, year) and check whether there is any bias. Provide both the code and your interpretation.

In [21]:
df['region'].value_counts()
df['type'].value_counts()
df['year'].value_counts()

year
2017    5722
2016    5616
2015    5615
2018    1300
1904       1
Name: count, dtype: int64

1.2 Write Python code to check for duplicate rows and missing values in the dataset. Show the number of duplicates and missing values for each column. Then, explain (in comments or markdown) how you would handle these issues (e.g., drop, impute, or replace).

In [10]:
df.duplicated().sum()
df.isnull().sum()

Column 1        0
Date            0
AveragePrice    0
Total Volume    1
4046            2
4225            1
4770            1
Total Bags      1
Small Bags      2
Large Bags      2
XLarge Bags     1
type            1
year            0
region          0
dtype: int64

1.3 Use Python code to print the number of rows and columns in the dataset (e.g., with df.shape). Based on the dataset size, explain (briefly) whether you think the dataset is sufficient for training a machine learning model.

In [11]:
df.shape

(18254, 14)

#2. Data Cleaning and Preprocessing

2.1 Remove the first column or “Column 1” from the dataset. Treat the ‘year’ variable as nominal.

In [12]:
df = df.drop(columns=['Column 1'])
df.head()

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,12-27-2015,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,12-20-2015,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,12-13-2015,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,12-6-2015,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,11-29-2015,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany

2.2 Check for duplicate values and remove them.

In [14]:
df.duplicated().sum()
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

2.3 Check for missing values. If a data record (row) only has a few missing values, replace the missing values with the median of the column feature in that specific “Region” variable. If most column values in a data record are missing, remove the data record.

In [25]:
df.isnull().sum()
df["Region"].fillna(df["Region"].median(), inplace=True)
df.isnull().sum()
df = df.dropna()
df.isnull().sum()

KeyError: 'Region'

2.4 Find the correlation between the variables and describe how the correlated values among the variables impact the model accuracy.

In [26]:
df.corr()

ValueError: could not convert string to float: '12-27-2015'

#3. Exploratory Data Analysis (EDA)

3.1 Describe the variables
- Describe all variables in the dataset.
- For continuous variables: report **range (min, max), mean, median, and distribution**.
- For categorical variables: list unique values.

In [17]:
df.describe()
df['region'].unique()
df['type'].unique()
df['year'].unique()

array([2015, 2016, 2017, 2018, 1904])

3.2 Inspect the earliest recorded date
- Find the earliest `Date`.
- Check if there are avocado prices recorded from the earliest date up to 2010.
- Comment: does the earliest data point look reasonable? Keep or remove?

In [37]:
df["Date"].min()
df["Date"].max()

'9-6-2015'

3.3 Highest average price
- Find the highest value in "AveragePrice".
- Report which region it belongs to.
- Describe how you obtained the result.

In [18]:
df[df['AveragePrice'] == df['AveragePrice'].max()]

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
14125,10-30-2016,3.25,16700.94,2325.93,11142.85,0.0,3232.16,3232.16,0.0,0.0,organic,2016,SanFrancisco

3.4 Highest total volume
- Find the highest total volume of avocados.
- Report which region it belongs to.
- Describe how you obtained the result.

In [19]:
df[df['Total Volume'] == df['Total Volume'].max()]

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
9097,2-4-2018,0.87,62505646.52,21620180.9,20445501.03,1066830.22,19373134.37,13384586.8,5719096.61,269450.96,conventional,2018,TotalUS